import crypto from 'node:crypto'

const users = new Map()
const projects = new Map()
const tasks = new Map()
const hash = (text) => crypto.createHash('sha256').update(text).digest('hex')
const sign = (payload) => { const body=Buffer.from(JSON.stringify(payload)).toString('base64url'); const secret=process.env.JWT_SECRET||'devflow-demo-secret'; const sig=crypto.createHmac('sha256',secret).update(body).digest('base64url'); return `${body}.${sig}` }
const verify = (token) => { try { const [body,sig]=String(token||'').split('.'); if(!body||!sig)return null; const secret=process.env.JWT_SECRET||'devflow-demo-secret'; const expected=crypto.createHmac('sha256',secret).update(body).digest('base64url'); if(sig!==expected)return null; return JSON.parse(Buffer.from(body,'base64url').toString()) } catch{return null} }
const now=()=>new Date().toISOString(), id=()=>crypto.randomUUID()
function seed(){ if(users.size)return; const u={_id:id(),name:'Alex Morgan',email:'demo@devflow.app',passwordHash:hash('Demo123!'),avatar:'AM'}; users.set(u._id,u); const p1={_id:id(),owner:u._id,name:'Nebula Mobile',description:'Launch the next-generation client experience.',color:'#6c5ce7',status:'active',dueDate:'2026-09-05'},p2={_id:id(),owner:u._id,name:'Pulse Analytics',description:'Make team performance visible at a glance.',color:'#16b6c9',status:'active',dueDate:'2026-09-12'}; projects.set(p1._id,p1);projects.set(p2._id,p2); [['Finalize onboarding flow',p1._id,'done','high'],['Wire API error states',p1._id,'in-progress','urgent'],['Polish empty states',p1._id,'todo','medium'],['Define KPI cards',p2._id,'done','medium'],['Build filters',p2._id,'in-progress','high'],['Connect analytics model',p2._id,'todo','medium']].forEach(([title,project,status,priority])=>{const t={_id:id(),owner:u._id,title,project,assignee:u._id,status,priority,dueDate:null,createdAt:now(),updatedAt:now(),description:''};tasks.set(t._id,t)}) }
seed()
async function body(req){if(req.body!==undefined)return typeof req.body==='string'?JSON.parse(req.body||'{}'):req.body||{};return await new Promise((resolve,reject)=>{let d='';req.on('data',c=>d+=c);req.on('end',()=>{try{resolve(d?JSON.parse(d):{})}catch(e){reject(e)}});req.on('error',reject)})}
function json(res,status,data){res.statusCode=status;res.setHeader('Content-Type','application/json');res.setHeader('Cache-Control','no-store');res.end(JSON.stringify(data))}
function cors(res){res.setHeader('Access-Control-Allow-Origin','*');res.setHeader('Access-Control-Allow-Headers','Content-Type, Authorization');res.setHeader('Access-Control-Allow-Methods','GET,POST,PATCH,DELETE,OPTIONS')}
function auth(req){const p=verify(req.headers.authorization?.replace(/^Bearer\s+/i,''));return p?users.get(p.sub):null}
function project(p){const ts=[...tasks.values()].filter(t=>t.project===p._id),done=ts.filter(t=>t.status==='done').length;return {...p,taskCount:ts.length,completed:done,progress:ts.length?Math.round(done/ts.length*100):0}}
function task(t){const p=projects.get(t.project),a=users.get(t.assignee);return {...t,project:p?{_id:p._id,name:p.name,color:p.color}:null,assignee:a?{_id:a._id,name:a.name,avatar:a.avatar}:null}}
function need(req,res){const u=auth(req);if(!u){json(res,401,{message:'Authentication required.'});return null}return u}
export default async function handler(req,res){cors(res);if(req.method==='OPTIONS')return json(res,204,{});const path=(req.url||'/').split('?')[0].replace(/^\/api/,'')||'/';try{
if(req.method==='GET'&&path==='/health')return json(res,200,{ok:true,service:'devflow-ai',mode:'vercel'})
if(req.method==='POST'&&path==='/auth/login'){const b=await body(req),u=[...users.values()].find(x=>x.email===String(b.email||'').trim().toLowerCase());if(!u||u.passwordHash!==hash(String(b.password||'')))return json(res,401,{message:'Invalid email or password.'});return json(res,200,{user:{_id:u._id,name:u.name,email:u.email,avatar:u.avatar},token:sign({sub:u._id})})}
if(req.method==='POST'&&path==='/auth/register'){const b=await body(req),email=String(b.email||'').trim().toLowerCase(),name=String(b.name||'').trim()||'New User',password=String(b.password||'');if(!email||password.length<6)return json(res,400,{message:'Email and a password of at least 6 characters are required.'});if([...users.values()].some(x=>x.email===email))return json(res,409,{message:'An account with this email already exists.'});const u={_id:id(),name,email,passwordHash:hash(password),avatar:name.split(' ').map(x=>x[0]).slice(0,2).join('').toUpperCase()};users.set(u._id,u);return json(res,201,{user:{_id:u._id,name:u.name,email:u.email,avatar:u.avatar},token:sign({sub:u._id})})}
const u=need(req,res);if(!u)return
if(req.method==='GET'&&path==='/dashboard'){const ps=[...projects.values()].filter(p=>p.owner===u._id).map(project),ts=[...tasks.values()].filter(t=>t.owner===u._id).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)),completed=ts.filter(t=>t.status==='done').length,active=ts.filter(t=>t.status==='in-progress').length,overdue=ts.filter(t=>t.dueDate&&new Date(t.dueDate)<new Date()&&t.status!=='done').length;return json(res,200,{stats:{projects:ps.length,tasks:ts.length,completed,active,overdue},projects:ps,tasks:ts.slice(0,8).map(task)})}
if(path==='/projects'&&req.method==='GET')return json(res,200,[...projects.values()].filter(p=>p.owner===u._id).map(project))
if(path==='/projects'&&req.method==='POST'){const b=await body(req),name=String(b.name||'').trim();if(!name)return json(res,400,{message:'Project name is required.'});const p={_id:id(),owner:u._id,name,description:String(b.description||''),color:b.color||'#6c5ce7',status:'active',dueDate:b.dueDate||null};projects.set(p._id,p);return json(res,201,project(p))}
const pm=path.match(/^\/projects\/([^/]+)$/);if(pm){const p=projects.get(pm[1]);if(!p||p.owner!==u._id)return json(res,404,{message:'Project not found.'});if(req.method==='GET')return json(res,200,project(p));if(req.method==='PATCH'){const b=await body(req);Object.assign(p,{name:b.name??p.name,description:b.description??p.description,status:b.status??p.status,dueDate:b.dueDate??p.dueDate});return json(res,200,project(p))}if(req.method==='DELETE'){projects.delete(p._id);for(const t of [...tasks.values()])if(t.project===p._id)tasks.delete(t._id);return json(res,200,{ok:true})}}
if(path==='/tasks'&&req.method==='GET')return json(res,200,[...tasks.values()].filter(t=>t.owner===u._id).map(task))
if(path==='/tasks'&&req.method==='POST'){const b=await body(req),p=projects.get(b.project);if(!p||p.owner!==u._id)return json(res,400,{message:'A valid project is required.'});const t={_id:id(),owner:u._id,title:String(b.title||'').trim(),description:String(b.description||''),project:p._id,assignee:b.assignee||u._id,status:b.status||'todo',priority:b.priority||'medium',dueDate:b.dueDate||null,createdAt:now(),updatedAt:now()};if(!t.title)return json(res,400,{message:'Task title is required.'});tasks.set(t._id,t);return json(res,201,task(t))}
const tm=path.match(/^\/tasks\/([^/]+)$/);if(tm){const t=tasks.get(tm[1]);if(!t||t.owner!==u._id)return json(res,404,{message:'Task not found.'});if(req.method==='PATCH'){const b=await body(req);Object.assign(t,{title:b.title??t.title,description:b.description??t.description,status:b.status??t.status,priority:b.priority??t.priority,dueDate:b.dueDate??t.dueDate});t.updatedAt=now();return json(res,200,task(t))}if(req.method==='DELETE'){tasks.delete(t._id);return json(res,200,{ok:true})}}
if(req.method==='POST'&&path==='/ai/generate-tasks'){const b=await body(req),brief=String(b.brief||'').trim()||'launch a new product',name=String(b.projectName||'New project');return json(res,200,{tasks:[{title:`Define success criteria for ${name}`,priority:'high',description:`Clarify outcomes, users, and measurable goals for ${brief}.`},{title:'Break the scope into milestones',priority:'high',description:'Turn the project goal into small, testable delivery milestones.'},{title:'Design the first usable flow',priority:'medium',description:'Map the key screens, states, and edge cases for the first release.'},{title:'Implement and validate the critical path',priority:'urgent',description:'Build the smallest end-to-end slice and verify it with real usage.'},{title:'Prepare launch checklist',priority:'medium',description:'Review quality, analytics, documentation, and deployment readiness.'}]})}
return json(res,404,{message:'Route not found.'})
}catch(e){console.error(e);return json(res,500,{message:'Unexpected server error.'})}}
